# 갑을병합치기

In [166]:
import pandas as pd

In [167]:
data = pd.read_excel('17대.xlsx')
data

,지역,선거인수,투표수,대통합민주신당 정동영,한나라당 이명박,민주노동당 권영길,민주당 이인제,창조한국당 문국현,참주인연합 정근모,겅제공화당 허경영,새시대참사람연합 전관,한국사회당 금민,무소속 이회창,계,무효,기권
0,서울 종로구,133946,85480,21515,45172,1889,398,5722,56,331,13,77,9984,85157,323,48466
1,서울 중구,106837,66496,17299,35335,1387,328,4324,33,240,9,52,7278,66285,211,40341
2,서울 용산구,190910,117051,25967,66096,2358,532,7544,78,486,12,77,13554,116704,347,73859
3,서울 성동구,266124,165391,41902,88602,3811,894,11330,100,727,38,118,17389,164911,480,100733
4,서울 광진구,297332,183412,46597,94864,4159,845,14052,106,943,33,114,21275,182988,424,113920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,경남 산청군,30086,21140,2055,12239,1482,87,552,11,93,13,35,4037,20604,536,8946
244,경남 거창군,50823,34594,3637,19863,1708,127,1345,26,128,20,45,6982,33881,713,16229
245,경남 합천군,45959,31741,2815,18867,1626,122,927,26,109,17,62,6339,30910,831,14218
246,제주 제주시,296325,181304,56798,70297,7059,1124,15142,114,929,90,227,27824,179604,1700,115021
247,제주 서귀포시,117697,70807,24772,26198,3895,550,4279,38,344,54,117,9671,69918,889,46890

In [168]:
filtered_data = data #.drop(data.index[0::2])
filtered_data

,지역,선거인수,투표수,대통합민주신당 정동영,한나라당 이명박,민주노동당 권영길,민주당 이인제,창조한국당 문국현,참주인연합 정근모,겅제공화당 허경영,새시대참사람연합 전관,한국사회당 금민,무소속 이회창,계,무효,기권
0,서울 종로구,133946,85480,21515,45172,1889,398,5722,56,331,13,77,9984,85157,323,48466
1,서울 중구,106837,66496,17299,35335,1387,328,4324,33,240,9,52,7278,66285,211,40341
2,서울 용산구,190910,117051,25967,66096,2358,532,7544,78,486,12,77,13554,116704,347,73859
3,서울 성동구,266124,165391,41902,88602,3811,894,11330,100,727,38,118,17389,164911,480,100733
4,서울 광진구,297332,183412,46597,94864,4159,845,14052,106,943,33,114,21275,182988,424,113920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,경남 산청군,30086,21140,2055,12239,1482,87,552,11,93,13,35,4037,20604,536,8946
244,경남 거창군,50823,34594,3637,19863,1708,127,1345,26,128,20,45,6982,33881,713,16229
245,경남 합천군,45959,31741,2815,18867,1626,122,927,26,109,17,62,6339,30910,831,14218
246,제주 제주시,296325,181304,56798,70297,7059,1124,15142,114,929,90,227,27824,179604,1700,115021
247,제주 서귀포시,117697,70807,24772,26198,3895,550,4279,38,344,54,117,9671,69918,889,46890

In [169]:
filtered_data.to_csv('17대_filtered.csv', index=False)

In [170]:
# Removing suffixes '갑', '을', '병' from the '지역' column
# filtered_data['지역'] = filtered_data['지역'].str.replace(r'갑|을|병', '', regex=True)

# Grouping by the modified '지역' column and summing up the other columns
grouped_df = filtered_data # .groupby('지역').sum().reset_index()

grouped_df

,지역,선거인수,투표수,대통합민주신당 정동영,한나라당 이명박,민주노동당 권영길,민주당 이인제,창조한국당 문국현,참주인연합 정근모,겅제공화당 허경영,새시대참사람연합 전관,한국사회당 금민,무소속 이회창,계,무효,기권
0,서울 종로구,133946,85480,21515,45172,1889,398,5722,56,331,13,77,9984,85157,323,48466
1,서울 중구,106837,66496,17299,35335,1387,328,4324,33,240,9,52,7278,66285,211,40341
2,서울 용산구,190910,117051,25967,66096,2358,532,7544,78,486,12,77,13554,116704,347,73859
3,서울 성동구,266124,165391,41902,88602,3811,894,11330,100,727,38,118,17389,164911,480,100733
4,서울 광진구,297332,183412,46597,94864,4159,845,14052,106,943,33,114,21275,182988,424,113920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,경남 산청군,30086,21140,2055,12239,1482,87,552,11,93,13,35,4037,20604,536,8946
244,경남 거창군,50823,34594,3637,19863,1708,127,1345,26,128,20,45,6982,33881,713,16229
245,경남 합천군,45959,31741,2815,18867,1626,122,927,26,109,17,62,6339,30910,831,14218
246,제주 제주시,296325,181304,56798,70297,7059,1124,15142,114,929,90,227,27824,179604,1700,115021
247,제주 서귀포시,117697,70807,24772,26198,3895,550,4279,38,344,54,117,9671,69918,889,46890

In [171]:
data_without_columns = grouped_df.drop(columns=['선거인수', '투표수', '계', '무효', '기권'])
data_without_columns

,지역,대통합민주신당 정동영,한나라당 이명박,민주노동당 권영길,민주당 이인제,창조한국당 문국현,참주인연합 정근모,겅제공화당 허경영,새시대참사람연합 전관,한국사회당 금민,무소속 이회창
0,서울 종로구,21515,45172,1889,398,5722,56,331,13,77,9984
1,서울 중구,17299,35335,1387,328,4324,33,240,9,52,7278
2,서울 용산구,25967,66096,2358,532,7544,78,486,12,77,13554
3,서울 성동구,41902,88602,3811,894,11330,100,727,38,118,17389
4,서울 광진구,46597,94864,4159,845,14052,106,943,33,114,21275
...,...,...,...,...,...,...,...,...,...,...,...
243,경남 산청군,2055,12239,1482,87,552,11,93,13,35,4037
244,경남 거창군,3637,19863,1708,127,1345,26,128,20,45,6982
245,경남 합천군,2815,18867,1626,122,927,26,109,17,62,6339
246,제주 제주시,56798,70297,7059,1124,15142,114,929,90,227,27824
247,제주 서귀포시,24772,26198,3895,550,4279,38,344,54,117,9671

In [172]:
data_without_columns.to_csv('17대_filtered1.csv', index=False)