In [1]:
import pandas as pd

data = pd.read_csv('20대_filtered1.csv')
data

,지역,더불어민주당 이재명,국민의힘 윤석열,정의당 심상정,기본소득당 오준호,국가혁명당 허경영,노동당 이백윤,새누리당 옥은호,신자유민주연합 김경재,우리공화당 조원진,진보당 김재연,통일한국당 이경희,한류연합당 이경희
0,서울 종로구,46130,49172,3115,53,558,42,9,50,82,105,20,30
1,서울 중구,38244,42906,2310,46,463,19,10,17,67,57,17,28
2,서울 용산구,60063,85047,4374,67,755,37,24,56,86,100,27,46
3,서울 성동구,84411,103880,5365,123,969,50,20,47,122,152,34,65
4,서울 광진구,109922,113733,7072,155,1416,52,36,62,180,172,38,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,경남 산청군,7125,16607,464,24,218,9,4,9,34,82,42,28
243,경남 거창군,11963,27254,895,46,490,19,18,12,42,92,62,52
244,경남 합천군,6911,22742,511,30,311,24,9,16,62,96,68,52
245,제주 제주시,157695,122084,10007,189,2496,108,46,80,193,395,159,197
246,제주 서귀포시,55435,50930,3591,78,1043,38,17,21,78,176,69,113

In [3]:
data.columns = [*data.columns[:-1], '한류연합당 김민찬']

In [4]:
data

,지역,더불어민주당 이재명,국민의힘 윤석열,정의당 심상정,기본소득당 오준호,국가혁명당 허경영,노동당 이백윤,새누리당 옥은호,신자유민주연합 김경재,우리공화당 조원진,진보당 김재연,통일한국당 이경희,한류연합당 김민찬
0,서울 종로구,46130,49172,3115,53,558,42,9,50,82,105,20,30
1,서울 중구,38244,42906,2310,46,463,19,10,17,67,57,17,28
2,서울 용산구,60063,85047,4374,67,755,37,24,56,86,100,27,46
3,서울 성동구,84411,103880,5365,123,969,50,20,47,122,152,34,65
4,서울 광진구,109922,113733,7072,155,1416,52,36,62,180,172,38,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,경남 산청군,7125,16607,464,24,218,9,4,9,34,82,42,28
243,경남 거창군,11963,27254,895,46,490,19,18,12,42,92,62,52
244,경남 합천군,6911,22742,511,30,311,24,9,16,62,96,68,52
245,제주 제주시,157695,122084,10007,189,2496,108,46,80,193,395,159,197
246,제주 서귀포시,55435,50930,3591,78,1043,38,17,21,78,176,69,113

In [5]:
data.to_csv('20대_filtered1.csv', index=False)